In [ ]:
# Sum Team ideas including TAs' advice on Thu 27, 2024:
#
# Project Goal is to Predict 2024's Trophy:
# 1.which country wins the most medals?
# 2.which country wins the most gold?
# 3.which country wins going to win the most silver?
# 4.which country wins going to win the most bronze?

# Year column is important (Agelica brought it back). 
# 2020 and 2016 are important (Sebas found 2016 and 2020 data. can we can fill them into current dataset?).
# Use Linear Regression for Summer Olympics dataset modeling
# StandardScale is not needed for Summer Olympics dataset modeling


# My thoughts:
# a) year column is important because of time carries the info of a country's change - mostly wealth and population.
#    Suggest to use year as reference to concate with other dataset such as Country (wealth, population) along time.
#    wealth and population can be classified as high-medium-low: 2-1-0
# b) year column is important also because of more recent years achievement (amount of medals won) have more impact to y.
#    suggest to calculate correclation coefficient of each reacent yeay to y and use it as a weight (or simply give 
#    (weight accorging to common sense) to improve model accuracy
# c) designing classification model will bring more chance to get hired in AI field because of the hot competition on 
#    recogniztion technilogies: manless driving, human face/sound-recognization, pet's recognization, etc. and I believe
#    in the future, human/machine(AI) recognization. Another reason for doing classification model is we have more tools
#    for model evaluation and optimization. So suggest:
#    c1) Implement project with two models: first step is Linear Regression model to find out most possible country and
#        all needed correlation coefficients. 
#    c2) second step is classification model focusing on most possible 5-10 countries with weight applied. weight = 
#        correlation coefficient from step 1 for each column.
# d) X=df['Year', 'Country'], where Year=1/(2024-Year) (already has weight in anscending order (impact of years back)
#    y=df{'Medal'], where Medal=sum(Gold,Silver,Bronze) if only predict total amount of medals of country    
# Finally the model predictions in my mind will be like:
# Score (or posibility) of country 1 winning the most medals = history_score * weight_h + wealth_score * weight_w + 
#                                                              population_score * weight_p + distance_score * weight_d) 
# where:  
# history_score = number of times having won trophy 1826-2020 * (1 + weight_2020_trophy + weight_2016_trophy) / total medals 
# reflecting the impact of a country's confidence and possession of talented atheletes.
# wealth_score = $ per capita / world's average (or use GPT)
# population_score = a country's population / world's average
# distance_score = distance from the city of games = 0 (on same continent) or 1 (not on same continent)

# Score (or posibility) of country 2 winning the most medals
# Score (or posibility) of country 3 winning the most medals
# ...
# Score (or posibility) of country 10 winning the most medals

# Which country has the highest score?

# Thoughts and work on 30 June 2024
# Guys, I think we have to trade off the project goal for data processing simplicity or the other way
# around:
# 1) predict 2016 instead of 2024 and use original dataset without having to concat the 2016/2020 data, or
# 2) keep project goal of predicting 2024 by keeping only Year, City, Country and Medal and dropping all
# all others for both datasets. Then concat with Country as reference.

# 2 July 2024 update
# non-linear model: polynomial (cubic) regression for S shape
Step 1: Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
Step 2: Importing the dataset
Step 3: Training the Polynomial Regression model on
the whole dataset


from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X)
# lin_reg = LinearRegression()
# lin_reg.fit(X_poly, y)

Step 4: Predicting the Results
y_pred = lin_reg.predict(X_poly)
Step 5: Comparing the Real Values with Predicted 
Values
df = pd.DataFrame({'Real Values':y, 'Predicted Values':y_pred})
df
Step 6: Visualising the Polynomial Regression results
X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(X, y, color = 'red')
plt.scatter(X, y_pred, color = 'green')
plt.plot(X_grid, lin_reg.predict(poly_reg.fit_transform(X_grid)), color = 'black')
plt.title('Polynomial Regression')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()





%matplotlib widget
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, OrdinalEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [15]:
# Load the dataset 1 (1896-2012)

## file_1_path = r"C:\Users\des9231\Desktop\boot_camp_assignment\M16_17_Project2\Summer-Olympics-2024-Predictive-Model\resource\summer_1.csv"
## df_1 = pd.read_csv(file_path)
## df_1.info()

# 30 june 2024 Use another dataset shared by Sebas (get around concate issue for adding 2016/2024 data) 

file_path = r"C:\Users\des9231\Desktop\boot_camp_assignment\M16_17_Project2\Summer-Olympics-2024-Predictive-Model\Resources\Summer_olympic_Medals.csv"
df = pd.read_csv(file_path)
# See 1) if the amount of records larger than 400; 2)amount od NaN; 3)dtypes; 4)columns) 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1344 entries, 0 to 1343
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Year          1344 non-null   int64
 1   Host_country  1344 non-null   object
 2   Host_city     1344 non-null   object
 3   Country_Name  1344 non-null   object
 4   Country_Code  1258 non-null   object
 5   Gold          1344 non-null   int64
 6   Silver        1344 non-null   int64
 7   Bronze        1344 non-null   int64
dtypes: int64(4), object(4)
memory usage: 84.1+ KB

In [18]:
# see dataset structure. noticed row 16: {Country_Name} = {Host_country}
df.head(20)

,Year,Host_country,Host_city,Country_Name,Country_Code,Gold,Silver,Bronze
0,1896,Greece,Athens,Great Britain,GBR,2,3,2
1,1896,Greece,Athens,Hungary,HUN,2,1,3
2,1896,Greece,Athens,France,FRA,5,4,2
3,1896,Greece,Athens,United States,USA,11,7,2
4,1896,Greece,Athens,Germany,GER,6,5,2
5,1896,Greece,Athens,Austria,AUT,2,1,2
6,1896,Greece,Athens,Mixed team,ZZX,1,0,1
7,1896,Greece,Athens,Greece,GRE,10,18,19
8,1896,Greece,Athens,Switzerland,SUI,1,2,0
9,1896,Greece,Athens,Australia,AUS,2,0,0
10,1896,Greece,Athens,Denmark,DEN,1,2,3
11,1900,France,Paris,Italy,ITA,3,2,0
12,1900,France,Paris,Germany,GER,4,3,2
13,1900,France,Paris,Australia,AUS,2,0,3
14,1900,France,Paris,Hungary,HUN,1,2,2
15,1900,France,Paris,Denmark,DEN,1,3,2
16,1900,France,Paris,France,FRA,27,38,37
17,1900,France,Paris,Switzerland,SUI,6,2,1
18,1900,France,Paris,United States,USA,19,14,15
19,1900,France,Paris,Mixed team,ZZX,8,5,6

In [ ]:
# Which country won the most 'Gold' in history (previous years)?
# 1) sum medals: Gold + Silver + Bronze
# 2) list medal.value_count in ascending order
# 3) extract winner for each year. (now we have Year, Country_Name (winner), Medal_Amount, Host_country
# 4) Draw the line of Country_Name vs Year

In [14]:
# Drop the label to create the X data, assuming the "Athlete" are not important

# X = df.drop(columns=['Medal', '', 'Gender', 'Athlete', 'Discipline', 'Sport', 'City' ],  axis=1)
X = df.drop(columns=['Bronze', 'Silver', 'Gold', 'Country_Code', 'Host_city'],  axis=1)
X.head(20)

    Year Host_country   Country_Name
0   1896       Greece  Great Britain
1   1896       Greece        Hungary
2   1896       Greece         France
3   1896       Greece  United States
4   1896       Greece        Germany
5   1896       Greece        Austria
6   1896       Greece     Mixed team
7   1896       Greece         Greece
8   1896       Greece    Switzerland
9   1896       Greece      Australia
10  1896       Greece        Denmark
11  1900       France          Italy
12  1900       France        Germany
13  1900       France      Australia
14  1900       France        Hungary
15  1900       France        Denmark
16  1900       France         France
17  1900       France    Switzerland
18  1900       France  United States
19  1900       France     Mixed team

In [12]:
# Create the y set from the "Medal" column

y = df['Gold']
y

0        2
1        2
2        5
3       11
4        6
        ..
1339     1
1340     1
1341     1
1342     1
1343     1
Name: Gold, Length: 1344, dtype: int64

## Preprocess the data

In [ ]:
# Split the data into training and testing sets using random_state=1

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [ ]:
# Encode y data with Label Encoder. 

le = LabelEncoder()

y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.fit_transform(y_test)

In [ ]:
# Encode X data with Ordinal Encoder. 

#? X_train_encodered_discipl_event_gender = ohe.fit_transform(X_train['Discipline', 'Event', 'Gender']
#? X_test_encodered_discipl_event_gender = ohe.fit_transform(X_test['Discipline', 'Event', 'Gender']                                                      
#? oe = OrdinalEncoder()
#? X_train_encodered_country = oe.fit_transform(X_train['country']    
#? X_test_encodered_country = oe.fit_transform(X_test['country']

# encode_education = OrdinalEncoder(categories=[['primary', 'secondary', 'tertiary']], handle_unknown='use_encoded_value', unknown_value=-1)
# encode_education.fit(X_train_filled['education'].values.reshape(-1, 1))

oe = OrdinalEncoder()

X_train_encoded = oe.fit_transform(X_train)
X_test_encoded = oe.fit_transform(X_test)

X_train_encoded

In [ ]:
# Scale the X data by using StandardScaler()

scaler = StandardScaler().fit(X_train)

X_train_scaled = scaler.transform(X_train_encoded)
X_train_scaled

In [ ]:
# Transform the test dataset based on the fit from the training dataset

X_test_scaled = scaler.transform(X_test_encoded)
X_test_scaled

In [ ]:
# Scale y data

y_train_scaled = scaler.transform(y_train_encoded)
y_test_scaled = scaler.transform(y_test_encoded)

y_train_scaled

## Model and Fit to a Logistic Regression Classifier

In [ ]:
# Create the logistic regression classifier model with a random_state of 1

lr_model = LogisticRegression()

# Fit the model to the training data

lr_model.fit(X_train_scaled, y_train_scaled)

In [ ]:
# Validate the model by checking the model accuracy with model.score

print(f"Training Data Score: {lr_model.score(X_train_scaled, y_train_scaled)}")
print(f"Testing Data Score: {lr_model.score(X_test_scaled, y_test_scaled)}")

In [ ]:
# Overfitting, underfitting, or bias?

In [ ]:
# Variance tradeoff, or optimization?

In [ ]:
# Improve using hyperparameter tuning,  implement cross-validation techniques, Grid Search, and/or Randomized Search?

In [ ]:
# What are the common pitfalls using the Logistic Regression Classifier model?

## Model and Fit to a Support Vector Machine

In [ ]:
# Create the support vector machine classifier model with a 'rbf' kernel

svm_model = SVC(kernel='rbf')

# Fit the model to the training data

svm_model.fit(X_train_scaled, y_train_scaled)

In [ ]:
# Validate the model by checking the model accuracy with model.score
print(f"Training Data Score: {svm_model.score(X_train_scaled, y_train_scaled)}")
print(f"Testing Data Score: {svm_model.score(X_test_scaled, y_test_scaled)}")

## Model and Fit to a KNN Model

In [ ]:
# Loop k to find the best number of neighbors

import matplotlib.pyplot as plt
# Loop through different k values to find which has the highest accuracy.
# Note: We use only odd numbers because we don't want any ties.
train_scores = []
test_scores = []
for k in range(1, 20, 2):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled, y_train_scaled)
    train_score = knn.score(X_train_scaled, y_train_scaled)
    test_score = knn.score(X_test_scaled, y_test_scaled)
    train_scores.append(train_score)
    test_scores.append(test_score)
    print(f"k: {k}, Train/Test Score: {train_score:.3f}/{test_score:.3f}")
    
# Plot the results
plt.plot(range(1, 20, 2), train_scores, marker='o', label="training scores")
plt.plot(range(1, 20, 2), test_scores, marker="x", label="testing scores")
plt.xlabel("k neighbors")
plt.ylabel("accuracy score")
plt.legend()
plt.show()

In [ ]:
# Create the KNN model with ? neighbors

knn_model = KNeighborsClassifier(n_neighbors=?)

# Fit the model to the training data

knn_model.fit(X_train_scaled, y_train_scaled)

In [ ]:
# Validate the model by checking the model accuracy with model.score

print(f"Training Data Score: {knn_model.score(X_train_scaled, y_train_scaled)}")
print(f"Testing Data Score: {knn_model.score(X_test_scaled, y_test_scaled)}")

## Model and Fit to a Decision Tree Classifier

In [ ]:
# Create the decision tree classifier model

dt_model = DecisionTreeClassifier()

# Fit the model to the training data

dt_model.fit(X_train_scaled, y_train_scaled)

In [ ]:
# Validate the model by checking the model accuracy with model.score

print(f"Training Data Score: {dt_model.score(X_train_scaled, y_train_scaled)}")
print(f"Testing Data Score: {dt_model.score(X_test_scaled, y_test_scaled)}")

## Model and Fit to a Random Forest Classifier

In [ ]:
# Create the random forest classifier model
# with n_estimators=128 and random_state=1

rf_model = RandomForestClassifier(n_estimators=128, random_state=1)

# Fit the model to the training data

rf_model.fit(X_train_scaled, y_train_scaled)

In [ ]:
# Validate the model by checking the model accuracy with model.score

print(f"Training Data Score: {rf_model.score(X_train_scaled, y_train_scaled)}")
print(f"Testing Data Score: {rf_model.score(X_test_scaled, y_test_scaled)}")

In [ ]:
# Which model has the highest accuracy, lrc, svm, knn, dtc, or rfc?

In [ ]:
####### Using confusion matrix to further evaluate the most accurate model 

from sklearn.metrics import confusion_matrix, classification_report, balanced_accuracy_score, roc_auc_score

# Create a confusion matrix
print(confusion_matrix(y, predictions, labels = [1,0]))

# Create a classification report
print(classification_report(y, predictions, labels = [1, 0]))

# Calculate the balanced accuracy score
print(balanced_accuracy_score(y, predictions))

# Predict values with probabilities
pred_probas = classifier.predict_proba(X)

# Print the probabilities
pred_probas

# Each prediction includes a prediction for both the 0 class and the 1 class
# We only need the predictions for the 1 class; use a list comprehension to 
# gather the second value from each list

pred_probas_firsts = [prob[1] for prob in pred_probas]

# Print the first 5 probabilities
pred_probas_firsts[0:5]

# Calculate the roc_auc_score
print(roc_auc_score(y, pred_probas_firsts))

In [ ]:
# Visualizing with confusion matrix, pie chart and Histogram

In [ ]:
# Next Steps 
# 1) Refine the model by concatenating with other dataset(s) such as: Country dataset with info on Wealthy level (Dollar Per 
# Capita), Location (Europe, North America, Asia, South America, Africa, ...), Population level (Large, Medium, Small), 
# Women participation rate, etc.
# 2) Optimize the model by assigning different weight for each column according to its correlation (impact) to y.
# 3) Using the same workframe but different dataset to build a model for Europe Cup 2024: Who will win the trophy?
# 4) Build any model by adding weights according to our own expereince. Comment the bias introduced by human beings.
# Are we able to fully eliminate bias?